### ISSUE TITLE
Robot Drive Output not updated often enough

### ISSUE THREAD

**Issue by TheMDev** [Team-2502/UpdatedRobotCode2017#28]
ERROR  1  Robot Drive... Output not updated often enough.  java.lang.Thread.run(Thread.java:745) 
    Error at java.lang.Thread.run(Thread.java:745): Robot Drive... Output not updated often enough.

[Possible Fix](http://wpilib.screenstepslive.com/s/4485/m/13809/l/599705-using-the-motor-safety-feature)

**Comment by isaacaj** [comment]
Fixed it by removing the `drive.setExpiration(x);` line from the DriveTrainSubsystem class.
